### ISSUE TITLE
API Promotion to cluster MuleESB nodes

### ISSUE THREAD

**Issue by siddharthgrd** [mulesoft-consulting/automated_api_promotion#1]
Hi Team,

Query-
Could you please advise if this promotion tool will promote both API/API Instances to both the nodes in the Cluster configuration having two nodes in the same network?

Nodes:targetserver1 & targetserver2 (two nodes)
Hope the targetserver type will be cluster?

For that shall I enter the below in promotion_config.yml 

Organisation: "IRMulesoftCrowd"
SourceEnvName: "TEST"
SourceServerName: "ContainerizedCluster"
SourceServerType: "sourceserver"
TargetEnvName: "Pre-Prod"
TargetServerName: "targetserver1,targetserver2"
TargetServerType: "CLUSTER"
Applications:
- 
appName: "ir-s-customer"
apiInstanceId: 9546857

Thanks,
Siddharth

**Comment by igor-repka** [comment]
Hi Siddharth,
Yes it is supported. `TargetServerName` would be the name of your cluster in Runtime Manager. Please, find example below:

```
Config:
  Organisation: "IRMulesoftCrowd"		
  SourceEnvName: "TEST"				
  SourceServerName: "ContainerizedCluster"
  SourceServerType: "CLUSTER"			
  TargetEnvName: "PROD"				
  TargetServerName: "ClusterName"			
  TargetServerType: "CLUSTER"		
  Applications:	
    - 
      appName: "ir-s-customer"			
      apiInstanceId: 9546857
```
